odiseo_sylius_banner_plugin_admin_banner:
    resource: |
        alias: odiseo_sylius_banner_plugin.banner
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        grid: odiseo_sylius_banner_plugin_banner
        permission: true
        vars:
            all:
                templates:
                    form: '@OdiseoSyliusBannerPlugin/Admin/Banner/_form.html.twig'
            index:
                icon: image
    type: sylius.resource


odiseo_sylius_banner_plugin_admin_banner_archive:
    path: /banners/{id}/archive
    methods: [PATCH]
    defaults:
        _controller: odiseo_sylius_banner_plugin.controller.banner:updateAction
        _sylius:
            section: admin
            permission: true
            template: '@SyliusUi/Grid/Action/archive.html.twig'
            form:
                type: Sylius\Bundle\ResourceBundle\Form\Type\ArchivableType
            redirect:
                route: odiseo_sylius_banner_plugin_admin_banner_index
                parameters: {}
